enable_dashboard: yes
listen_port: 8888
hide_logs: yes
node_down_alert_minutes: 3
prometheus_enabled: yes
prometheus_listen_port: 28686

telegram:
  enabled: yes
  api_key: '${API_KEY}'

chains:
  # Will be populated dynamically based on user registrations
