backup_nodes:
  template:
    rpc_endpoints:
      nibiru:
        - "https://nibiru.rpc.kjnodes.com"
        - "https://rpc.nibiru.nodestake.org"
        - "https://rpc.lavenderfive.com:443/nibiru"
      zetachain:
        - "https://zetachain-mainnet-archive.allthatnode.com:26657"
        - "https://rpc.lavenderfive.com:443/zetachain"
        - "https://rpc.zetachain.nodestake.org"
