bot:
  settings:
    default_monitoring_interval: 300  # 5 minutes
    max_alerts_per_hour: 10
    alert_cooldown: 300  # 5 minutes
    
  alert_thresholds:
    missed_blocks: 5
    sync_behind_blocks: 100
    peer_count_min: 3
    
  monitoring:
    intervals:
      quick: 60
      normal: 300
      relaxed: 900
