networks:
  nibiru:
    name: "Nibiru Chain"
    chain_id: "cataclysm-1"
    logo_png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/nibiru/images/nibiru.png"
    rpc_endpoint: "https://rpc.nibiru.fi"
  zetachain:
    name: "Zeta Chain"
    chain_id: "zetachain_7000-1"
    logo_png: "https://raw.githubusercontent.com/CoinHuntersTR/Logo/main/zetachain-icon.png"
    rpc_endpoint: "https://zetachain.blockpi.network/rpc/v1/public"
